name: danger-ci

on:
  pull_request:
    branches: "*"

jobs:
  build:
    # 実行環境はmacosに設定
    runs-on: macos-latest

    steps:
      # fetch-depth の計算
      - run: echo "fetch_depth=$(( commits + 1 ))" >> $GITHUB_ENV
        env:
          commits: ${{ github.event.pull_request.commits }}

      # チェックアウト(リポジトリからソースコードを取得)
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: ${{ env.fetch_depth }}

      # danger jsのインストール
      - name: Install Danger JS
        run: npm install -g danger

      # Dangerモジュールをビルド
      - name: Build Swift Package
        run: swift build -c release
        working-directory: Dangerfile

      # dangerを実行
      - name: Analytics with danger
        run: |
          swift run -c release danger-swift ci --cwd ../ --verbose --failOnErrors --no-publish-check
        working-directory: Dangerfile
        env:
          # Dangerはプルリクエストを読み取ってコメントをするので、必要な権限を持ったGithubトークンを渡してあげる必要がある
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_BOT_GITHUB_TOKEN }}
